[GoldenDict]
Executable=goldendict
; Dictionary group name in GoldenDict
DefaultGroupName=default
; GoldenDict → Edit → Preferences → Hotkeys → "... translate a word from clipboard" toggle: on=on, off=off(default)
ClipboardHotkeyEnabled=off

[Hotkeys]
; Hotkey to bind/unbind window
ToggleKey=^!+g

; Default is %EDITOR%, fallback notepad
[AutoHotkey]
ScriptEditor=