[GoldenDict]
Executable=goldendict
; Dictionary group for DoubleClick mode
DoubleClickGroup=default
; Dictionary group for Clipboard mode
ClipboardGroup=translate
; GoldenDict → Edit → Preferences → Hotkeys → "... translate a word from clipboard" toggle: on=on, off=off(default)
ClipboardHotkeyEnabled=off

[Settings]
; Double-click to select and search, no clipboard pollution
DoubleClickEnabled=on
; Auto-search when clipboard content changes
ClipboardEnabled=off

[Hotkeys]
; Hotkey to bind/unbind window
ToggleKey=^!+g

; Default is %EDITOR%, fallback notepad
[AutoHotkey]
ScriptEditor=
